name: Hadoop Demo

on: [workflow_dispatch]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        
    - name: Run Hadoop Demo
      run: |
        chmod +x run-job.sh
        ./run-job.sh
